### ISSUE TITLE
Created AVIF files don't display in Firefox

### ISSUE THREAD

**Issue by Lenni009** [0xC0000054/pdn-avif#23] opened 2023-06-04 10:44 UTC
When converting a jpg to AVIF using PDN, Firefox says the file has errors when trying to load it.

This does not happen in Chrome, it displays the file perfectly fine.
I believe this is an issue with PDN because Firefox can load other AVIF images just fine.
If you convert the jpg to AVIF using an online converter, it also works perfectly fine in Firefox.

The [AVIF validator](https://gpac.github.io/ComplianceWarden-wasm/avif.html) spits out multiple warnings about tile widths and heights that they should be multiples of 64.

Used software:
Paint dot net 5.0.6
Firefox 113.0.2
Chrome 114

**Comment by 0xC0000054** [comment] 2023-06-04 13:04
What are the dimensions of the image you are trying to save?

>  I believe this is an issue with PDN because Firefox can load other AVIF images just fine.

I suspect it is an existing [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1696090) in Firefox's AVIF support, Firefox does not support loading AVIF files that use an image grid.
As a workaround, you can save the image using the Very Slow compression preset.

This Paint.NET plugin uses an image grid to reduce memory usage and improve UI responsiveness when encoding AVIF images.

> The AVIF validator spits out multiple warnings about tile widths and heights that they should be multiples of 64.

I was unaware of that tile size recommendation. It appears that libavif also ignores it when creating grid images: 
```c
// The priority could be to use a cell size that is a multiple of 64, but there is not always a valid one,
// even though it is recommended by MIAF. Just use ceil(numPixels/numCells) for simplicity and to avoid
// as much padding in the right-most and bottom-most cells as possible.
```
https://github.com/AOMediaCodec/libavif/blob/454adbf5c27d24e1645cae53c1c659d46e07f657/apps/avifenc.c#L533

**Comment by Lenni009** [comment] 2023-06-04 13:21
The image is 800x600px. The "Very Slow" preset workaround worked, thanks! I tested all presets, only the "Fast" one has that error in FF.

I also opened a bug on Bugzilla, so hopefully this can also be fixed on Firefox' side.
Thanks again!

**Comment by 0xC0000054** [comment] 2023-06-04 14:52
> The image is 800x600px. The "Very Slow" preset workaround worked, thanks! I tested all presets, only the "Fast" one has that error in FF.

That confirms that it is the same Firefox bug I mentioned in my previous post.

>I also opened a bug on Bugzilla, so hopefully this can also be fixed on Firefox' side.

Could you post a link in that issue to: https://bugzilla.mozilla.org/show_bug.cgi?id=1696090
Your issue is a duplicate of that one.

**Closed as not planned** 2024-01-12 02:31 UTC
