### ISSUE TITLE
Saving at 100% quality produces corrupted colors (in some other apps)

### ISSUE THREAD

**Issue by rickbrew** [0xC0000054/pdn-avif#10] opened 2020-08-30 00:59 UTC
I haven't tested this myself yet, but looks important:

https://blog.getpaint.net/2020/08/25/paint-net-4-2-14-alpha-build-7542/#comment-21610

![image](https://user-images.githubusercontent.com/10873410/91648840-5212b700-ea21-11ea-9fd5-64b63d08f654.png)

**Comment by 0xC0000054** [comment] 2020-08-30 02:08
It is a known bug in with some AVIF decoders, they do not correctly handle images that use the CICP Identity matrix and treat those images as if they use YUV.
Unfortunately the OP did not specify what decoder they are using, but both Microsoft's HEIF Image Extensions (release date 1/29/2018) and Firefox (version 80.0) have this issue.
The images are decoded correctly in Chrome (version 85.0).

The CICP Identity matrix is a color encoding that allows RGB colors to be used without conversion to the YUV color space, this allows for fully lossless RGB encoding.
libavif has the same issue with lossless RGB encoding, https://github.com/AOMediaCodec/libavif/issues/243.

**Comment by LaaZa** [comment] 2020-08-30 12:27
At least XnView MP has this issue, I can see it in thumbnails too but I'm not sure if XnView is the provider for those or something else. Seems to be using libavif (c) 2019. I guess this just needs to be fixed in those affected decoders then. I assume that because 100% is lossless RGB then the chroma subsampling has no effect, should this be made clear in the UI? Currently it is possible to change the setting at 100% without it having any effect.

**Comment by 0xC0000054** [comment] 2020-08-30 13:50
> I assume that because 100% is lossless RGB then the chroma subsampling has no effect, should this be made clear in the UI? Currently it is possible to change the setting at 100% without it having any effect.

I could make the chroma subsampling setting read only when the quality setting is set to 100, but the chroma subsampling is also ignored for monochrome images and `paint.net` does not currently allow FileType plugins to configure UI based on the image content.

It would be confusing if the UI had different behavior for those two cases.

**Comment by rickbrew** [comment] 2020-08-30 21:08
The fact that the preview in Paint.NET _doesn't_ show corrupted colors is further proof that the bug actually lies elsewhere -- the preview is powered by saving to a temp file and then loading it back.

**Comment by LaaZa** [comment] 2020-08-31 09:35
I have to admit that I have not looked at the preview even once because it takes so long to load(was at normal/medium by default though), a general problem with AV1/AVIF I know. Would it be too fancy to only make a preview of a smaller portion of the image if the image is over certain size? 
Took a very long time to preview a 18 MP image from my camera at 100% slow(I know slow is slow but the time it took is absurd). I've had my pc just melt trying to encode AV1 in general. Not sure what kind of logic Paint.net allows with these.

Actually assuming the preview is full size, couldn't Paint.net just save that preview if you save the image when the preview is done. Right now after I wait for a preview, possibly for a long while, after I save it it'll just take as long to actually save.

Sorry I'm getting slightly off topic. I think what is happening is definitely some decoders(or their specific use) assuming the image is YUV when it in fact is RGB, the resulting colours also look something like that. Like changing your monitor's color space to YUV when the input is actually RGB, looks similar.

**Comment by 0xC0000054** [comment] 2020-08-31 12:19
> I think what is happening is definitely some decoders(or their specific use) assuming the image is YUV when it in fact is RGB, the resulting colours also look something like that.

That is what would be happening when the quality is at 100%.

**Comment by LaaZa** [comment] 2020-09-02 09:07
Actually interestingly enough XnView MP shows properly in the image properties that the images are RGB lossless, however their ExifTool shows YUV 4:4:4.

Edit: nevermind the properties seems to always say Color model: RGB while YUV is shown in the Color format, it still says lossless.

**Comment by 0xC0000054** [comment] 2020-09-11 23:55
Closing this issue as it is not a bug in the plugin.

**Closed as completed by 0xC0000054** 2020-09-11 23:55 UTC
Labels: wontfix
